apiVersion: v1
kind: Service
metadata:
  name: web-html
  labels:
    app: web-html
spec:
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
  selector:
    app: web-html
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  labels:
    app: web-html
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-html
  labels:
    app: web-html
spec:
  selector:
    matchLabels:
      app: web-html
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web-html
    spec:
      containers:
      - image: httpd
        name: web-html
        volumeMounts:
        - name: web-html-persistent-storage
         mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: web-html-persistent-storage
          persistentVolumeClaim:
            claimName: web-pvc
